name: 'Build and force redeploy'
description: 'Build and push new image to AWS ECR and force new deployment of ECS service'
inputs:
  ecr-registry:
    description: 'ECR registry'
    required: true
  ecr-repository:
    description: 'ECR repository'
    required: true
  image-tag:
    description: 'Image tag. Defaults to latest'
    required: true
    default: 'latest'
  ecs-service:
    description: 'ECS service name'
    required: true
runs:
  using: "composite"
  steps: 
    - name: Build, tag, push to AWS ECR
      id: build
      run: |
        docker build -t ${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}:${{ inputs.image-tag }} .
        docker push ${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}:${{ inputs.image-tag }}
        echo "::set-output name=image::${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}:${{ inputs.image-tag }}"
      shell: bash
    - name : Force new deployment
      run: |
        aws ecs update-service --cluster default --service ${{ ecs-service }} --force-new-deployment
      shell: bash
